### ISSUE TITLE
Is it possible for you to also create a gem for bootstrap_sb_admin also?

### ISSUE THREAD

**Issue by ghost** [dreamingechoes/bootstrap_sb_admin_base_v2#13]
Hey man! This gem integrated bootstrap_sb_admin2 is really great and saves me tons of time. Many thanks for your great work.🤝

Just want to know if you would also integrate [bootstrap_sb_admin](https://startbootstrap.com/template-overviews/sb-admin/) and create a gem like bootstrap_sb_admin_base_v1? Because me personally like the above theme more than v2.😅

This is just a request and you may ignore and close it if you don't have time or would not plan to do this.

If support against v1 is not in your plan scope, I will try to do it myself referencing your project.

Many thanks in advance.

**Comment by dreamingechoes** [comment]
Hi @nathanaelyang830427!

I could make a gem for that theme, of course, the problem it's "when" haha 😄

During the week I'm quite busy with my work, I could search time this weekend to do it. If I finally don't manage to have some free time to make the gem, don't hesitate to do it yourself, sure! I will let you know in this issue anyways.

Greetings! 😄

**Comment by dreamingechoes** [comment]
Hi @nathanaelyang830427!

I made a quick first version of the [bootstrap_sb_admin](https://startbootstrap.com/template-overviews/sb-admin/) as a rails gem, you can check it [here](https://github.com/dreamingechoes/bootstrap_sb_admin_base_v1). I've done it in a couple of hours, so maybe it could have some mistakes.

Could you test it and give me some feedback to see if all works properly? 

Thank you! 😄

**Comment by ghost** [comment]
Hi @dreamingechoes ,

Awesome! 🙊

I will test it and give feedback soon. Really appreciate your hard work and generosity.

**Comment by ghost** [comment]
Hi @dreamingechoes ,

Just replaced v2 with v1 and made necessary adjustments mainly consisting of page change, style synchronization and etc. Actually within 30 minutes all changed to v1 theme. Easy to use and integrate. Good job!👏

Currently I only faced a little issue that the font is smaller than expected, I will investigate more and give feedback then, I guess this might be due to some coding issue I made.

I will report issue(if there is any) and give feedback in the v1 project. I'd like to close this issue as it has been resolved far beyond my expectations.
