### ISSUE TITLE
Font awesome

### ISSUE THREAD

**Issue by themire** [dreamingechoes/bootstrap_sb_admin_base_v2#2]
I get fontawesome-webfont-v=4.2.0.woff  not found when I try to deploy this to Heroku.

Is there anything else that needs to be done to get the fonts working?

**Comment by dreamingechoes** [comment]
Hi!

this week I'm going to release a new version of the gem for add the RTL version, so I'll fix this bug too. Thank you for the feedback about this bug!

**Comment by themire** [comment]
Ok cool, thanks. It's also throwing an error about missing glyphicons fonts.

**Comment by dreamingechoes** [comment]
Hi!

I've just released a new version (0.2.1) of the gem to fix this problem. 

Here you have an example application using this new version, so you can see that works just fine: https://sensor-admin-panel-testing.herokuapp.com (testing user: example@email.com, password: 123456example).

Thank you!
